name: "Semgrep Scan - Nightly @ 7am EST"


on:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 7:00 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >- 
            p/default
        continue-on-error: true

      - name: List directory contents
        run: |
          echo "Current directory contents:"
          ls -la

      - name: Capture Semgrep output
        run: |
          semgrep --config=auto --json > semgrep-results.json
        continue-on-error: true

      - name: Display Semgrep results
        run: |
          if [ -f semgrep-results.json ]; then
            echo "Semgrep JSON output:"
            cat semgrep-results.json
          else
            echo "semgrep-results.json not found"
          fi

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-results
          path: semgrep-results.json
